// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7gTDNLxBfkP1ljCA5S5RakAPX8PFwhUA',
    appId: '1:819508295009:web:712f8e52dfd5fb25574120',
    messagingSenderId: '819508295009',
    projectId: 'cashswift-bad5e',
    authDomain: 'cashswift-bad5e.firebaseapp.com',
    storageBucket: 'cashswift-bad5e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF6LnGHA2p4E7LnJ1ARieXY_DVq2A_uVM',
    appId: '1:819508295009:android:f3a147f35d4be2a3574120',
    messagingSenderId: '819508295009',
    projectId: 'cashswift-bad5e',
    storageBucket: 'cashswift-bad5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEOXUC_7rJ-NbUZwS5WsSTxqJZRFLqz_k',
    appId: '1:819508295009:ios:de859cc0ce4a0fe1574120',
    messagingSenderId: '819508295009',
    projectId: 'cashswift-bad5e',
    storageBucket: 'cashswift-bad5e.appspot.com',
    iosBundleId: 'com.example.cashswift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEOXUC_7rJ-NbUZwS5WsSTxqJZRFLqz_k',
    appId: '1:819508295009:ios:58500c6dab57bae5574120',
    messagingSenderId: '819508295009',
    projectId: 'cashswift-bad5e',
    storageBucket: 'cashswift-bad5e.appspot.com',
    iosBundleId: 'com.example.cashswift.RunnerTests',
  );
}
